definitions:
  auth.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginResp:
    properties:
      access_token:
        type: string
      expires_at:
        type: integer
      type:
        type: string
    type: object
  auth.MeResp:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  auth.RegisterReq:
    properties:
      email:
        example: admin@go-framework.com
        type: string
      name:
        example: zhan
        type: string
      password:
        example: "123456"
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  description: gin framework
  license:
    name: none
  title: go-framework
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      description: 登录
      parameters:
      - description: 登录
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResp'
      summary: 登录
  /api/v1/auth/register:
    post:
      description: 注册新用户
      parameters:
      - description: 注册信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 注册新用户
  /api/v1/me:
    get:
      description: 获取当前登录用户信息
      parameters:
      - description: accessToken
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.MeResp'
      summary: 获取当前登录用户信息
swagger: "2.0"
